# Generated by Django 3.1.5 on 2021-01-22 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAdvertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.IntegerField()),
                ('views', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('baseadvertise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertiser_management.baseadvertise')),
                ('username', models.CharField(max_length=30)),
            ],
            bases=('advertiser_management.baseadvertise',),
        ),
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('baseadvertise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertiser_management.baseadvertise')),
                ('title', models.CharField(max_length=30)),
                ('image_url', models.URLField()),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('advertiser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.advertiser')),
            ],
            bases=('advertiser_management.baseadvertise',),
        ),
    ]
