# Generated by Django 3.1.5 on 2021-01-24 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertiser_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertiser',
            options={'ordering': ['id'], 'verbose_name': 'Advertiser'},
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Advertiser', to=settings.AUTH_USER_MODEL),
        ),
    ]
