# Generated by Django 3.1.5 on 2021-01-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='email',
            field=models.EmailField(default='Google@gmail.com', max_length=254),
        ),
    ]
