# Generated by Django 3.1.5 on 2021-01-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0002_ad_approve'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedAd',
            fields=[
            ],
            options={
                'verbose_name': 'Requested Ad',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('advertiser_management.ad',),
        ),
    ]
