# Generated by Django 3.1.5 on 2021-01-23 17:21

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0003_auto_20210123_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertiser',
            options={'verbose_name': 'Advertiser'},
        ),
        migrations.AlterModelManagers(
            name='advertiser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='advertise',
            name='image_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='baseadvertise',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='baseadvertise',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
