from model import *

baseAdvertising = BaseAdvertising()
advertiser1 = Advertiser('masoud')
advertiser2 = Advertiser('human')
ad1 = Ad('title1', 'img-url1', 'link1', advertiser1)
ad2 = Ad('title2', 'img-url2', 'link2', advertiser2)
print(baseAdvertising.describe_me())
print(ad2.describe_me())
print(advertiser1.describe_me())
ad1.increase_views()
ad1.increase_views()
ad1.increase_views()
ad1.increase_views()
ad2.increase_views()
ad1.increase_clicks()
ad1.increase_clicks()
ad2.increase_clicks()
print(advertiser2.get_name())
advertiser2.set_name('new name')
print(advertiser2.get_name())
print(ad1.get_clicks())
print(advertiser2.get_clicks())
print(f'Total views {Advertiser.get_total_views()}')
print(f'Total clicks {Advertiser.get_total_clicks()}')
print(Advertiser.help())
